export default [
  { text: "Actions", value: "actions" },
  { text: "Article", value: "article" },
  { text: "Avatar", value: "avatar" },
  { text: "Button", value: "button" },
  { text: "Card", value: "card" },
  { text: "Card + Avatar", value: "card-avatar" },
  { text: "Card + Heading", value: "card-heading" },
  { text: "Chip", value: "chip" },
  { text: "Datepicker", value: "date-picker" },
  { text: "Datepicker + Options", value: "date-picker-options" },
  { text: "Datepicker + Days", value: "date-picker-days" },
  { text: "Heading", value: "heading" },
  { text: "Image", value: "image" },
  { text: "List Item", value: "list-item" },
  { text: "List Item + Avatar", value: "list-item-avatar" },
  { text: "List Item Two Line", value: "list-item-two-line" },
  { text: "List Item + Avatar Two Line", value: "list-item-avatar-two-line" },
  { text: "List Item Three Line", value: "list-item-three-line" },
  {
    text: "List Item + Avatar Three Line",
    value: "list-item-avatar-three-line"
  },
  { text: "Paragraph", value: "paragraph" },
  { text: "Sentences", value: "sentences" },
  { text: "Table", value: "table" },
  { text: "Table Heading", value: "table-heading" },
  { text: "Table Head", value: "table-thead" },
  { text: "Table Body", value: "table-tbody" },
  { text: "Table Row Divider", value: "table-row-divider" },
  { text: "Table Row", value: "table-row" },
  { text: "Table Cell", value: "table-cell" },
  { text: "Table Footer", value: "table-tfoot" },
  { text: "Text", value: "text" }
];
